version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000" 
    environment:
      - DB_HOST=db  
      - DB_PORT=5432
      - DB_NAME=wallet
      - DB_USER=postgres
      - DB_PASS=${DB_PASS}  
      - SECRET_KEY=${SECRET_KEY}  
    depends_on:
      - db  

  db:
    image: postgres:latest 
    restart: always
    environment:
      POSTGRES_DB: wallet  
      POSTGRES_USER: postgres  
      POSTGRES_PASSWORD: ${DB_PASS} 
    ports:
      - "5432:5432"
